project_id = "eiezckbfjwmrluloxusv"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.get-summary]
verify_jwt = false

[functions.list-transactions]
verify_jwt = false

[functions.create-transaction]
verify_jwt = false

[functions.delete-transaction]
verify_jwt = false

[functions.check-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.create-category]
verify_jwt = false

[functions.list-categories]
verify_jwt = false

[functions.create-credit-card]
verify_jwt = false
