// lovexit-exporter — generated by Lovexit
// Project: f0ddbb09-c51e-444b-9b62-f24b2b94b8ad
// Paste this as a new Supabase Edge Function named "lovexit-exporter".
// Uses SUPABASE_SERVICE_ROLE_KEY (auto-injected) for full read access.

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const SHARED_SECRET = "68921661addd6c28746b5ffad2125feb160f9042e8842c125fc5c8de1ebeffb3";
const LOVEXIT_ORIGIN = "*";
const PROJECT_ID = "f0ddbb09-c51e-444b-9b62-f24b2b94b8ad";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const DB_URL = Deno.env.get("SUPABASE_DB_URL") ?? "";

const admin = createClient(SUPABASE_URL, SERVICE_ROLE, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const cors = {
  "access-control-allow-origin": LOVEXIT_ORIGIN,
  "access-control-allow-methods": "GET,POST,OPTIONS",
  "access-control-allow-headers": "authorization,content-type,x-lovexit-secret",
};

function unauthorized(msg = "unauthorized") {
  return new Response(JSON.stringify({ error: msg }), {
    status: 401,
    headers: { "content-type": "application/json", ...cors },
  });
}

function json(body: unknown, init: ResponseInit = {}) {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: { "content-type": "application/json", ...cors, ...(init.headers ?? {}) },
  });
}

async function handshake() {
  const { error } = await admin.from("pg_tables").select("schemaname").limit(1);
  return {
    ok: !error,
    project_id: PROJECT_ID,
    supabase_url: SUPABASE_URL,
    has_db_url: Boolean(DB_URL),
    sample_error: error?.message ?? null,
    timestamp: new Date().toISOString(),
  };
}

async function listPublicTables(): Promise<string[]> {
  const { data } = await admin
    .from("information_schema.tables")
    .select("table_name")
    .eq("table_schema", "public")
    .eq("table_type", "BASE TABLE");
  return (data ?? []).map((r: { table_name: string }) => r.table_name);
}

async function introspect() {
  const tables = await listPublicTables();
  const { data: users } = await admin.auth.admin
    .listUsers({ page: 1, perPage: 1 })
    .catch(() => ({ data: { total: 0 } } as unknown as { data: { total: number } }));
  const { data: buckets } = await admin.storage.listBuckets().catch(() => ({ data: [] }));
  return {
    project_id: PROJECT_ID,
    supabase_url: SUPABASE_URL,
    auth_users_count: (users as { total?: number })?.total ?? 0,
    storage_buckets: buckets ?? [],
    tables: tables.map((t) => ({ table_schema: "public", table_name: t })),
    captured_at: new Date().toISOString(),
  };
}

async function dumpTableRows(table: string, maxRows = 50000) {
  const rows: unknown[] = [];
  const pageSize = 1000;
  let from = 0;
  while (rows.length < maxRows) {
    const { data, error } = await admin
      .from(table)
      .select("*")
      .range(from, from + pageSize - 1);
    if (error) return { table, error: error.message, rows: [] };
    if (!data || data.length === 0) break;
    rows.push(...data);
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return { table, rows };
}

async function dumpAuthUsers(maxPages = 50) {
  const all: unknown[] = [];
  for (let page = 1; page <= maxPages; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) return { error: error.message, users: all };
    const u = (data as { users?: unknown[] })?.users ?? [];
    all.push(...u);
    if (u.length < 200) break;
  }
  return { users: all };
}

async function dumpStorageManifest() {
  const { data: buckets } = await admin.storage.listBuckets();
  const out: Array<{ bucket: string; public: boolean; objects: unknown[] }> = [];
  for (const b of buckets ?? []) {
    const objs: unknown[] = [];
    let offset = 0;
    while (true) {
      const { data } = await admin.storage
        .from(b.id)
        .list("", { limit: 1000, offset, sortBy: { column: "name", order: "asc" } });
      if (!data || data.length === 0) break;
      objs.push(...data);
      if (data.length < 1000) break;
      offset += 1000;
    }
    out.push({ bucket: b.id, public: b.public, objects: objs });
  }
  return out;
}

async function dump() {
  const tables = await listPublicTables();
  const tableDumps = [] as Array<{ table: string; rows: unknown[]; error?: string }>;
  for (const t of tables) {
    tableDumps.push(await dumpTableRows(t));
  }
  const auth = await dumpAuthUsers();
  const storage = await dumpStorageManifest();
  return {
    project_id: PROJECT_ID,
    supabase_url: SUPABASE_URL,
    captured_at: new Date().toISOString(),
    tables: tableDumps,
    auth,
    storage,
    note: "Row data exported via PostgREST as service_role. For binary-perfect dump use pg_dump with SUPABASE_DB_URL.",
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });

  const secret = req.headers.get("x-lovexit-secret");
  if (secret !== SHARED_SECRET) return unauthorized("bad shared secret");

  const url = new URL(req.url);
  const action = url.searchParams.get("action") ?? "handshake";

  try {
    if (action === "handshake") return json(await handshake());
    if (action === "introspect") return json(await introspect());
    if (action === "dump") return json(await dump());
    return json({ error: "unknown action" }, { status: 400 });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, { status: 500 });
  }
});
